name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          SSH_KEY_FILE=$(mktemp)
          echo "$VPS_SSH_KEY" > $SSH_KEY_FILE
          chmod 600 $SSH_KEY_FILE

          ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE -p $VPS_PORT $VPS_USER@$VPS_HOST '
            set -e # 遇到错误立即退出
            cd /home/deployer/taxonomy &&
            # 强制加载 bashrc 或 zshrc
            if [ -f ~/.bashrc ]; then
                source ~/.bashrc
            fi &&
            whoami &&
            echo "User: $(whoami)" &&
            echo "Shell: $SHELL" &&
            echo "PATH: $PATH" &&
            # 查找并杀死监听 3030 端口的进程
            PID=$(lsof -t -i :3030)
            if [ -n "$PID" ]; then
              kill $PID
            fi &&
            # 更新代码
            git pull &&
            # 确保 pnpm 使用的是正确的版本
            nvm use 18 &&
            npm i -g pnpm &&
            # 重新启动进程
            nohup /usr/local/bin/pnpm preview > /home/deployer/taxonomy/preview.log 2>&1 &
          '

          rm -f $SSH_KEY_FILE
