name: Deploy to VPS

on:
  push:
    branches:
      - main # 或者你想要监听的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/deployer/taxonomy
            git pull origin main # 假设你的主分支是 main，如果不是请替换

            # --- 查找并关闭旧进程 ---
            PORT=$(node -e "console.log(process.env.PORT || 3000)") # 获取端口号，这里假设你的应用默认端口是 3000，或者从环境变量 PORT 中读取
            if ! command -v fuser &> /dev/null
            then
              echo "fuser is not installed, please install it if you need to kill process by port."
              exit 1
            fi

            PROCESS_ID=$(fuser -k ${PORT}/tcp 2>/dev/null) # 尝试查找并关闭占用端口的进程，-k 会发送 SIGKILL 信号
            if [ -n "${PROCESS_ID}" ]; then
              echo "Killed process(es) on port ${PORT}: ${PROCESS_ID}"
              sleep 5 # 等待进程完全关闭，避免端口立即被占用
            else
              echo "No process found on port ${PORT}"
            fi
            # --- 关闭旧进程结束 ---

            pnpm preview
